name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: ffmpeg-dependencies
      run: |
        sudo apt update && sudo apt install -y g++ \
          curl \
          unzip \
          tar \
          yasm \
          make \
          build-essential \
          libx11-dev \
          libpthread-stubs0-dev \
          cmake
  
    - name: run-vcpkg
      uses: lukka/run-vcpkg@v6.0
      id: runvcpkg
      with:
        vcpkgArguments: ffmpeg:x64-linux catch2:x64-linux 
        vcpkgDirectory: ${{ runner.workspace }}/ffmpeg-cpp/dependencies/vcpkg/
        vcpkgTriplet: x64-linux
        appendedCacheKey: 'vcpkg-dependencies'
    
    - name: Run CMake with Ninja
      uses: lukka/run-cmake@v3
      id: runcmake
      with:
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        useVcpkgToolchainFile: true
        buildDirectory: '${{ github.workspace }}/build'
        buildWithCMakeArgs: '-- -v'

    - name: Run Test
      run: |
        pushd build
        ctest -V
    